map path to related items
stolostron/search-v2-api pull request #173
Opened 2023-08-10 20:56 UTC by SherinV

### Related Issue

https://issues.redhat.com/browse/ACM-0000

### Description of changes
- Added ...

2023-08-16 15:52 UTC, jlpadilla requested changes
@philipwu08 @SherinV I want to replace the words "parent" and "child" in this PR.  Not all relations are parent-child, it is only one type of relationship.
To avoid confusion, let's use something more generic like `relatedUid`.

2023-08-22 16:15 UTC, SherinV commented
> 

Replaced

2023-08-22 20:15 UTC, SherinV commented
/retest

2023-08-25 16:14 UTC, jlpadilla commented on pkg/resolver/related.go
> +// map the related result uids to the uids in the search input
```suggestion
// Maps the related result uids to the uids in the search result set.
```

2023-08-25 16:20 UTC, jlpadilla commented on pkg/resolver/related.go
> +func checkIfInArray(lookupMap []string, uid string) bool {
Just FYI, go 1.21 will add a new standard package `slices` to simplify this. It also has a `slices.Sort()` which we have somewhere else in this project.
https://pkg.go.dev/slices

2023-08-25 16:21 UTC, jlpadilla approved these changes
/lgtm
/hold

2023-08-28 14:31 UTC, SherinV commented
/retest

2023-08-28 16:40 UTC, merged